fix: should match dots
prettier/prettier-eslint-cli pull request #132
Opened 2018-05-09 09:51 UTC by u3u

I hope it can format and repair all matching files in my project, but I found that it did not format my configuration file (eg: .eslintrc.js, .postcssrc.js, etc.)

```json
"format": "prettier-eslint \"**/*.{js,json,vue,md}\" --write"
```

https://github.com/isaacs/node-glob#dots

2019-08-15 11:36 UTC, Oligrand commented
@kentcdodds @zimme 
Any chance we could get this merged? Or at least give us the option to control the `dot` option of glob? It would be nice to also get files starting with a dot prettified :)

2021-03-06 22:09 UTC, kylemh commented
@u3u feel free to resolve merge conflicts

@Oligrand feel free to open a new PR with the same fixes here if above doesn't happen fast enough for you!

2022-07-31 15:36 UTC, JounQin commented
Dot files are excluded by ESLint and prettier by default AFAIK, maybe this new feature should be behind a flag?

2022-08-25 08:17 UTC, JounQin commented
I think this should be implemented under a flag, can `false` by default same as ESLint and prettier.

2022-08-25 08:32 UTC, JounQin requested changes

2022-08-25 08:32 UTC, JounQin commented on src/format-files.js
> +  const globOptions = { dot: true, ignore: ignoreGlobs };
TODO: add a flag instead.

2022-08-25 10:19 UTC, kylemh commented
I think a `includeDotFiles` flag is good; however, you touched on a good point with the ignore files. If we WERE to respect those, how would we do it?

I can see at least 2 ways:
1. Use each ignore file for their respective runner. So, if ONLY a prettier ignore file exists, the eslint portion of our task will complete as expected and only the prettier portion would adhere to the ignore file.
2. We merge the ignore files and avoid those files for our entire runner.

2022-08-25 11:43 UTC, JounQin commented
> Use each ignore file for their respective runner. 

I review the source codes we're using this approach now: https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L206-L236

So we'll only need to support a `includeDotFiles` flag.

2022-08-25 11:43 UTC, JounQin commented
> Use each ignore file for their respective runner. 

I review the source codes we're using this approach now: https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L206-L236

So we'll only need to support a `includeDotFiles` flag.

2022-08-25 11:43 UTC, JounQin commented
> Use each ignore file for their respective runner. 

I review the source codes we're using this approach now: https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L206-L236

So we'll only need to support a `includeDotFiles` flag.

2022-08-25 12:42 UTC, JounQin approved these changes

2022-08-25 12:52 UTC, JounQin commented
TODO: document

2022-08-25 13:18 UTC, kylemh approved these changes

2022-08-25 13:23 UTC, merged